// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hapi/version/version.proto

package cn.com.chinacloud.paas.hapi.version;

public final class VersionOuterClass {
  private VersionOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface VersionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:hapi.version.Version)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Sem ver string for the version
     * </pre>
     *
     * <code>optional string sem_ver = 1;</code>
     */
    java.lang.String getSemVer();
    /**
     * <pre>
     * Sem ver string for the version
     * </pre>
     *
     * <code>optional string sem_ver = 1;</code>
     */
    com.google.protobuf.ByteString
        getSemVerBytes();

    /**
     * <code>optional string git_commit = 2;</code>
     */
    java.lang.String getGitCommit();
    /**
     * <code>optional string git_commit = 2;</code>
     */
    com.google.protobuf.ByteString
        getGitCommitBytes();

    /**
     * <code>optional string git_tree_state = 3;</code>
     */
    java.lang.String getGitTreeState();
    /**
     * <code>optional string git_tree_state = 3;</code>
     */
    com.google.protobuf.ByteString
        getGitTreeStateBytes();
  }
  /**
   * Protobuf type {@code hapi.version.Version}
   */
  public  static final class Version extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:hapi.version.Version)
      VersionOrBuilder {
    // Use Version.newBuilder() to construct.
    private Version(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Version() {
      semVer_ = "";
      gitCommit_ = "";
      gitTreeState_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Version(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              semVer_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              gitCommit_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              gitTreeState_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.com.chinacloud.paas.hapi.version.VersionOuterClass.internal_static_hapi_version_Version_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.com.chinacloud.paas.hapi.version.VersionOuterClass.internal_static_hapi_version_Version_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.com.chinacloud.paas.hapi.version.VersionOuterClass.Version.class, cn.com.chinacloud.paas.hapi.version.VersionOuterClass.Version.Builder.class);
    }

    public static final int SEM_VER_FIELD_NUMBER = 1;
    private volatile java.lang.Object semVer_;
    /**
     * <pre>
     * Sem ver string for the version
     * </pre>
     *
     * <code>optional string sem_ver = 1;</code>
     */
    public java.lang.String getSemVer() {
      java.lang.Object ref = semVer_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        semVer_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Sem ver string for the version
     * </pre>
     *
     * <code>optional string sem_ver = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSemVerBytes() {
      java.lang.Object ref = semVer_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        semVer_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GIT_COMMIT_FIELD_NUMBER = 2;
    private volatile java.lang.Object gitCommit_;
    /**
     * <code>optional string git_commit = 2;</code>
     */
    public java.lang.String getGitCommit() {
      java.lang.Object ref = gitCommit_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        gitCommit_ = s;
        return s;
      }
    }
    /**
     * <code>optional string git_commit = 2;</code>
     */
    public com.google.protobuf.ByteString
        getGitCommitBytes() {
      java.lang.Object ref = gitCommit_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        gitCommit_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GIT_TREE_STATE_FIELD_NUMBER = 3;
    private volatile java.lang.Object gitTreeState_;
    /**
     * <code>optional string git_tree_state = 3;</code>
     */
    public java.lang.String getGitTreeState() {
      java.lang.Object ref = gitTreeState_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        gitTreeState_ = s;
        return s;
      }
    }
    /**
     * <code>optional string git_tree_state = 3;</code>
     */
    public com.google.protobuf.ByteString
        getGitTreeStateBytes() {
      java.lang.Object ref = gitTreeState_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        gitTreeState_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getSemVerBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, semVer_);
      }
      if (!getGitCommitBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, gitCommit_);
      }
      if (!getGitTreeStateBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, gitTreeState_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getSemVerBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, semVer_);
      }
      if (!getGitCommitBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, gitCommit_);
      }
      if (!getGitTreeStateBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, gitTreeState_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.com.chinacloud.paas.hapi.version.VersionOuterClass.Version)) {
        return super.equals(obj);
      }
      cn.com.chinacloud.paas.hapi.version.VersionOuterClass.Version other = (cn.com.chinacloud.paas.hapi.version.VersionOuterClass.Version) obj;

      boolean result = true;
      result = result && getSemVer()
          .equals(other.getSemVer());
      result = result && getGitCommit()
          .equals(other.getGitCommit());
      result = result && getGitTreeState()
          .equals(other.getGitTreeState());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + SEM_VER_FIELD_NUMBER;
      hash = (53 * hash) + getSemVer().hashCode();
      hash = (37 * hash) + GIT_COMMIT_FIELD_NUMBER;
      hash = (53 * hash) + getGitCommit().hashCode();
      hash = (37 * hash) + GIT_TREE_STATE_FIELD_NUMBER;
      hash = (53 * hash) + getGitTreeState().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.com.chinacloud.paas.hapi.version.VersionOuterClass.Version parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.com.chinacloud.paas.hapi.version.VersionOuterClass.Version parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.com.chinacloud.paas.hapi.version.VersionOuterClass.Version parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.com.chinacloud.paas.hapi.version.VersionOuterClass.Version parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.com.chinacloud.paas.hapi.version.VersionOuterClass.Version parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.com.chinacloud.paas.hapi.version.VersionOuterClass.Version parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.com.chinacloud.paas.hapi.version.VersionOuterClass.Version parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.com.chinacloud.paas.hapi.version.VersionOuterClass.Version parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.com.chinacloud.paas.hapi.version.VersionOuterClass.Version parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.com.chinacloud.paas.hapi.version.VersionOuterClass.Version parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.com.chinacloud.paas.hapi.version.VersionOuterClass.Version prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code hapi.version.Version}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:hapi.version.Version)
        cn.com.chinacloud.paas.hapi.version.VersionOuterClass.VersionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.com.chinacloud.paas.hapi.version.VersionOuterClass.internal_static_hapi_version_Version_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.com.chinacloud.paas.hapi.version.VersionOuterClass.internal_static_hapi_version_Version_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.com.chinacloud.paas.hapi.version.VersionOuterClass.Version.class, cn.com.chinacloud.paas.hapi.version.VersionOuterClass.Version.Builder.class);
      }

      // Construct using cn.com.chinacloud.paas.hapi.version.VersionOuterClass.Version.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        semVer_ = "";

        gitCommit_ = "";

        gitTreeState_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.com.chinacloud.paas.hapi.version.VersionOuterClass.internal_static_hapi_version_Version_descriptor;
      }

      public cn.com.chinacloud.paas.hapi.version.VersionOuterClass.Version getDefaultInstanceForType() {
        return cn.com.chinacloud.paas.hapi.version.VersionOuterClass.Version.getDefaultInstance();
      }

      public cn.com.chinacloud.paas.hapi.version.VersionOuterClass.Version build() {
        cn.com.chinacloud.paas.hapi.version.VersionOuterClass.Version result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cn.com.chinacloud.paas.hapi.version.VersionOuterClass.Version buildPartial() {
        cn.com.chinacloud.paas.hapi.version.VersionOuterClass.Version result = new cn.com.chinacloud.paas.hapi.version.VersionOuterClass.Version(this);
        result.semVer_ = semVer_;
        result.gitCommit_ = gitCommit_;
        result.gitTreeState_ = gitTreeState_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.com.chinacloud.paas.hapi.version.VersionOuterClass.Version) {
          return mergeFrom((cn.com.chinacloud.paas.hapi.version.VersionOuterClass.Version)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.com.chinacloud.paas.hapi.version.VersionOuterClass.Version other) {
        if (other == cn.com.chinacloud.paas.hapi.version.VersionOuterClass.Version.getDefaultInstance()) return this;
        if (!other.getSemVer().isEmpty()) {
          semVer_ = other.semVer_;
          onChanged();
        }
        if (!other.getGitCommit().isEmpty()) {
          gitCommit_ = other.gitCommit_;
          onChanged();
        }
        if (!other.getGitTreeState().isEmpty()) {
          gitTreeState_ = other.gitTreeState_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.com.chinacloud.paas.hapi.version.VersionOuterClass.Version parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.com.chinacloud.paas.hapi.version.VersionOuterClass.Version) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object semVer_ = "";
      /**
       * <pre>
       * Sem ver string for the version
       * </pre>
       *
       * <code>optional string sem_ver = 1;</code>
       */
      public java.lang.String getSemVer() {
        java.lang.Object ref = semVer_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          semVer_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Sem ver string for the version
       * </pre>
       *
       * <code>optional string sem_ver = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSemVerBytes() {
        java.lang.Object ref = semVer_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          semVer_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Sem ver string for the version
       * </pre>
       *
       * <code>optional string sem_ver = 1;</code>
       */
      public Builder setSemVer(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        semVer_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Sem ver string for the version
       * </pre>
       *
       * <code>optional string sem_ver = 1;</code>
       */
      public Builder clearSemVer() {
        
        semVer_ = getDefaultInstance().getSemVer();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Sem ver string for the version
       * </pre>
       *
       * <code>optional string sem_ver = 1;</code>
       */
      public Builder setSemVerBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        semVer_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object gitCommit_ = "";
      /**
       * <code>optional string git_commit = 2;</code>
       */
      public java.lang.String getGitCommit() {
        java.lang.Object ref = gitCommit_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          gitCommit_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string git_commit = 2;</code>
       */
      public com.google.protobuf.ByteString
          getGitCommitBytes() {
        java.lang.Object ref = gitCommit_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          gitCommit_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string git_commit = 2;</code>
       */
      public Builder setGitCommit(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        gitCommit_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string git_commit = 2;</code>
       */
      public Builder clearGitCommit() {
        
        gitCommit_ = getDefaultInstance().getGitCommit();
        onChanged();
        return this;
      }
      /**
       * <code>optional string git_commit = 2;</code>
       */
      public Builder setGitCommitBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        gitCommit_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object gitTreeState_ = "";
      /**
       * <code>optional string git_tree_state = 3;</code>
       */
      public java.lang.String getGitTreeState() {
        java.lang.Object ref = gitTreeState_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          gitTreeState_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string git_tree_state = 3;</code>
       */
      public com.google.protobuf.ByteString
          getGitTreeStateBytes() {
        java.lang.Object ref = gitTreeState_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          gitTreeState_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string git_tree_state = 3;</code>
       */
      public Builder setGitTreeState(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        gitTreeState_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string git_tree_state = 3;</code>
       */
      public Builder clearGitTreeState() {
        
        gitTreeState_ = getDefaultInstance().getGitTreeState();
        onChanged();
        return this;
      }
      /**
       * <code>optional string git_tree_state = 3;</code>
       */
      public Builder setGitTreeStateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        gitTreeState_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:hapi.version.Version)
    }

    // @@protoc_insertion_point(class_scope:hapi.version.Version)
    private static final cn.com.chinacloud.paas.hapi.version.VersionOuterClass.Version DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.com.chinacloud.paas.hapi.version.VersionOuterClass.Version();
    }

    public static cn.com.chinacloud.paas.hapi.version.VersionOuterClass.Version getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Version>
        PARSER = new com.google.protobuf.AbstractParser<Version>() {
      public Version parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Version(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Version> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Version> getParserForType() {
      return PARSER;
    }

    public cn.com.chinacloud.paas.hapi.version.VersionOuterClass.Version getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_hapi_version_Version_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_hapi_version_Version_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032hapi/version/version.proto\022\014hapi.versi" +
      "on\"F\n\007Version\022\017\n\007sem_ver\030\001 \001(\t\022\022\n\ngit_co" +
      "mmit\030\002 \001(\t\022\026\n\016git_tree_state\030\003 \001(\tB%\n#cn" +
      ".com.chinacloud.paas.hapi.versionb\006proto" +
      "3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_hapi_version_Version_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_hapi_version_Version_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_hapi_version_Version_descriptor,
        new java.lang.String[] { "SemVer", "GitCommit", "GitTreeState", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
